// Generated by CoffeeScript 1.6.3
(function() {
  var i, _i;

  for (i = _i = 1; _i <= 100; i = ++_i) {
    if (i % 5 === 0 && i % 3 === 0) {
      console.log("fizzbuzz");
    } else if (i % 3 === 0) {
      console.log("fizz");
    } else if (i % 5 === 0) {
      console.log("buzz");
    } else {
      console.log(i);
    }
  }

}).call(this);
